#Plantear una situaciÃ³n donde podamos obtener el
#siguiente error:


2.3.1 :001 > def suma(a, b)
2.3.1 :002?>   return a + b
2.3.1 :003?>   end
=begin => :suma 
#2.3.1 :004 > puts suma(5)
ArgumentError: wrong number of arguments (given 1, expected 2)
  from (irb):1:in `suma'
  from (irb):4
  from /home/alvaro/.rvm/rubies/ruby-2.3.1/bin/irb:11:in `<main>'
